cc:
	clear
	@echo "-> Componentes Conexos - QuickFind"
	gcc cc_qf.c
	./a.out
	@echo "-> Componentes Conexos - DFS"
	gcc cc_dfs.c
	./a.out
	@echo "-> Comparando as saidas..."
	diff saida_qf.txt saida_dfs.txt